
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from blog.models import Post, Comment
import random
import uuid


User = get_user_model()


def _unique_slug(base):
    slug = slugify(base)[:180]
    # ensure uniqueness by appending short uuid if needed
    if Post.objects.filter(slug=slug).exists():
        slug = f"{slug}-{uuid.uuid4().hex[:6]}"
    return slug


class Command(BaseCommand):
    help = 'Generate sample users, blog posts and comments for local development'

    def add_arguments(self, parser):
        parser.add_argument('--users', type=int, default=3, help='Number of sample users to create')
        parser.add_argument('--posts', type=int, default=4, help='Number of posts per user')
        parser.add_argument('--comments', type=int, default=3, help='Max number of comments per post')
        parser.add_argument('--password', type=str, default='password123', help='Password for generated users')

    def handle(self, *args, **options):
        num_users = options['users']
        posts_per_user = options['posts']
        max_comments = options['comments']
        password = options['password']

        created_users = []
        self.stdout.write('Creating users...')
        for i in range(num_users):
            username = f'sampleuser{i+1}'
            email = f'{username}@example.com'
            user, created = User.objects.get_or_create(username=username, defaults={'email': email})
            if created:
                user.set_password(password)
                user.save()
                self.stdout.write(f'  Created user: {username} / {password}')
            else:
                self.stdout.write(f'  Reused user: {username}')
            created_users.append(user)

        # Create posts
        total_posts = 0
        total_comments = 0
        self.stdout.write('\nCreating posts and comments...')
        sample_paragraph = (
            "This is a sample post generated for testing. "
            "You can edit or delete these posts. "
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
        )

        for user in created_users:
            for p in range(posts_per_user):
                title = f"Sample Post {p+1} by {user.username}"
                slug = _unique_slug(title)
                content = sample_paragraph * random.randint(2, 6)
                excerpt = ' '.join(content.split()[:30])
                status = 1  # publish by default for visibility
                post = Post.objects.create(
                    title=title,
                    slug=slug,
                    author=user,
                    content=content,
                    excerpt=excerpt,
                    status=status,
                )
                total_posts += 1

                # randomly add comments (0..max_comments)
                num_comments = random.randint(0, max_comments)
                for c in range(num_comments):
                    commenter = random.choice(created_users)
                    body = f"Comment {c+1} on {title} — generated by {commenter.username}."
                    approved = random.choice([True, False])
                    Comment.objects.create(post=post, author=commenter, body=body, approved=approved)
                    total_comments += 1

        self.stdout.write(f'\nDone: created {len(created_users)} users, {total_posts} posts, {total_comments} comments')
        self.stdout.write('Sample users (password printed above) — you can delete them after testing.')
