# Generated by Django 5.2.8 on 2025-11-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('leaf', 'Leaf'), ('root', 'Root'), ('tuber', 'Tuber'), ('stalk', 'Stalk'), ('fruit', 'Fruit'), ('mushroom', 'Mushroom'), ('seed', 'Seed'), ('cereal', 'Cereal'), ('legume', 'Legume'), ('nut', 'Nut'), ('spice', 'Spice')])),
                ('sowing_range', models.DateField()),
                ('harvestring_range', models.DateField()),
                ('life_cycle', models.CharField(choices=[('perennial', 'Perennial'), ('biennial', 'Biennial'), ('many_years', 'Many Years')], max_length=20)),
            ],
        ),
    ]
