# Generated by Django 4.2.25 on 2025-11-15 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('growing_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='harvestring_range',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='life_cycle',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='sowing_range',
        ),
        migrations.AddField(
            model_name='allotment',
            name='garden',
            field=models.CharField(default='garden', max_length=200),
        ),
        migrations.AddField(
            model_name='allotment',
            name='name',
            field=models.CharField(default='Allotment', max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Garden', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardener', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
