# Generated by Django 4.2.25 on 2025-11-16 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('growing_projects', '0002_remove_crop_harvestring_range_remove_crop_life_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='name',
        ),
        migrations.AddField(
            model_name='allotment',
            name='current_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotments', to='growing_projects.crop'),
        ),
        migrations.AddField(
            model_name='crop',
            name='common_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_date_earliest',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_date_latest',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='life_cycle',
            field=models.CharField(choices=[('perennial', 'Perennial'), ('biennial', 'Biennial'), ('annual', 'Annual')], max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sowing_date_earliest',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sowing_date_latest',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='description',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden', to='growing_projects.garden'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='type',
            field=models.CharField(choices=[('leaf', 'Leaf'), ('root', 'Root'), ('tuber', 'Tuber'), ('stalk', 'Stalk'), ('fruit', 'Fruit'), ('mushroom', 'Mushroom'), ('seed', 'Seed'), ('cereal', 'Cereal'), ('legume', 'Legume'), ('nut', 'Nut'), ('spice', 'Spice'), ('herb', 'Herb'), ('flower', 'Flower')], max_length=50),
        ),
    ]
