# Generated by Django 4.2.25 on 2025-11-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growing_projects', '0003_remove_crop_name_remove_garden_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='harvesting_date_earliest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvesting_date_latest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='life_cycle',
            field=models.CharField(blank=True, choices=[('perennial', 'Perennial'), ('biennial', 'Biennial'), ('annual', 'Annual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_date_earliest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_date_latest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
