# Generated by Django 4.2.25 on 2025-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growing_projects', '0004_alter_crop_harvesting_date_earliest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='common_name',
            field=models.CharField(blank=True, default='Please add common name', max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='life_cycle',
            field=models.CharField(blank=True, choices=[('perennial', 'Perennial'), ('biennial', 'Biennial'), ('annual', 'Annual'), ('ephemeral', 'Ephemeral')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='type',
            field=models.CharField(blank=True, choices=[('leaf', 'Leaf'), ('root', 'Root'), ('tuber', 'Tuber'), ('stalk', 'Stalk'), ('fruit', 'Fruit'), ('mushroom', 'Mushroom'), ('seed', 'Seed'), ('cereal', 'Cereal'), ('legume', 'Legume'), ('nut', 'Nut'), ('spice', 'Spice'), ('herb', 'Herb'), ('flower', 'Flower')], max_length=50),
        ),
    ]
