# Generated by Django 4.2.25 on 2025-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growing_projects', '0005_alter_crop_common_name_alter_crop_life_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='gardens', to='growing_projects.crop'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='common_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
