# Generated by Django 4.2.25 on 2025-11-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growing_projects', '0006_garden_crops_alter_crop_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
    ]
